venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña (confirmación)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña nueva (confirmación)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña restablecida en %(site_name)s"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña cambiada correctamente"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña (confirmación)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña nueva (confirmación)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña restablecida en %(site_name)s"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña cambiada correctamente"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_MX/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_MX/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_MX/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_MX/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña (confirmación)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña nueva (confirmación)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña restablecida en %(site_name)s"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña cambiada correctamente"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/ast/LC_MESSAGES/django.po:msgstr "Contraseña camudada con ésitu."
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/ast/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib64/python3.10/site-packages/django/contrib/auth/locale/ast/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib64/python3.10/site-packages/django/contrib/admin/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña nueva:"
venv/lib64/python3.10/site-packages/django/contrib/admin/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña nueva:"
venv/lib64/python3.10/site-packages/django/contrib/admin/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña nueva:"
venv/lib64/python3.10/site-packages/django/contrib/admin/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña nueva:"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña (confirmación)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña nueva (confirmación)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña restablecida en %(site_name)s"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña cambiada correctamente"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña (confirmación)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña nueva (confirmación)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña restablecida en %(site_name)s"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña cambiada correctamente"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_MX/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_MX/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_MX/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_MX/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña (confirmación)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña nueva (confirmación)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña restablecida en %(site_name)s"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña cambiada correctamente"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña antigua"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña (de nuevo)"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/ast/LC_MESSAGES/django.po:msgstr "Contraseña camudada con ésitu."
venv/lib/python3.10/site-packages/django/contrib/auth/locale/ast/LC_MESSAGES/django.po:msgstr "Contraseña"
venv/lib/python3.10/site-packages/django/contrib/auth/locale/ast/LC_MESSAGES/django.po:msgstr "Contraseña nueva"
venv/lib/python3.10/site-packages/django/contrib/admin/locale/es/LC_MESSAGES/django.po:msgstr "Contraseña nueva:"
venv/lib/python3.10/site-packages/django/contrib/admin/locale/es_VE/LC_MESSAGES/django.po:msgstr "Contraseña nueva:"
venv/lib/python3.10/site-packages/django/contrib/admin/locale/es_CO/LC_MESSAGES/django.po:msgstr "Contraseña nueva:"
venv/lib/python3.10/site-packages/django/contrib/admin/locale/es_AR/LC_MESSAGES/django.po:msgstr "Contraseña nueva:"
