# Generated by Django 5.0.1 on 2024-08-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cartaportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartaporte',
            table='cartaporte',
        ),
        migrations.AlterModelTable(
            name='cartaportedoc',
            table='cartaportedoc',
        ),
    ]
