# Generated by Django 5.0.1 on 2024-08-19 21:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cartaporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('txt0a', models.CharField(max_length=20, null=True)),
                ('txt00', models.CharField(max_length=20, null=True)),
                ('txt01', models.CharField(max_length=200, null=True)),
                ('txt02', models.CharField(max_length=200, null=True)),
                ('txt03', models.CharField(max_length=200, null=True)),
                ('txt04', models.CharField(max_length=200, null=True)),
                ('txt05', models.CharField(max_length=200, null=True)),
                ('txt06', models.CharField(max_length=200, null=True)),
                ('txt07', models.CharField(max_length=200, null=True)),
                ('txt08', models.CharField(max_length=200, null=True)),
                ('txt09', models.CharField(max_length=200, null=True)),
                ('txt10', models.CharField(max_length=200, null=True)),
                ('txt11', models.CharField(max_length=200, null=True)),
                ('txt12', models.CharField(max_length=200, null=True)),
                ('txt13', models.CharField(max_length=200, null=True)),
                ('txt14', models.CharField(max_length=200, null=True)),
                ('txt15', models.CharField(max_length=200, null=True)),
                ('txt16', models.CharField(max_length=800, null=True)),
                ('txt17', models.CharField(max_length=200, null=True)),
                ('txt18', models.CharField(max_length=200, null=True)),
                ('txt19_1', models.CharField(max_length=200, null=True)),
                ('txt19_2', models.CharField(max_length=200, null=True)),
                ('txt19_3', models.CharField(max_length=200, null=True)),
                ('txt19_4', models.CharField(max_length=200, null=True)),
                ('txt20_1', models.CharField(max_length=200, null=True)),
                ('txt20_2', models.CharField(max_length=200, null=True)),
                ('txt21', models.CharField(max_length=200, null=True)),
                ('txt22', models.CharField(max_length=200, null=True)),
                ('txt23', models.CharField(max_length=200, null=True)),
                ('txt24', models.CharField(max_length=200, null=True)),
                ('txt25', models.CharField(max_length=200, null=True)),
                ('txt26', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'declaraciondoc',
            },
        ),
        migrations.CreateModel(
            name='Declaracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('pais', models.CharField(max_length=30)),
                ('cartaporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cartaporte.cartaporte')),
            ],
            options={
                'db_table': 'declaracion',
            },
        ),
    ]
