# Generated by Django 5.0.1 on 2024-09-02 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_declaracion', '0002_initial'),
        ('app_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracion',
            name='declarante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaraciones_declarante', to='app_docs.cliente'),
        ),
        migrations.AddField(
            model_name='declaracion',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaraciones_destinatario', to='app_docs.cliente'),
        ),
        migrations.AddField(
            model_name='declaracion',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaraciones_remitente', to='app_docs.cliente'),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_declaracion.declaraciondoc'),
        ),
    ]
