# Generated by Django 5.0.1 on 2024-09-03 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_declaracion', '0003_declaracion_declarante_declaracion_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion',
            name='documento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_declaracion.declaraciondoc'),
        ),
    ]
