# Generated by Django 5.0.1 on 2024-09-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_declaracion', '0004_alter_declaracion_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
