# Generated by Django 5.0.1 on 2024-08-07 02:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cartaportes', '0001_initial'),
        ('appdocs', '0016_remove_manifiesto_cartaporte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifiestoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('txt0a', models.CharField(max_length=20, null=True)),
                ('txt00', models.CharField(max_length=20, null=True)),
                ('txt01', models.CharField(max_length=200, null=True)),
                ('txt02', models.CharField(max_length=200, null=True)),
                ('txt03', models.CharField(max_length=200, null=True)),
                ('txt04', models.CharField(max_length=200, null=True)),
                ('txt05', models.CharField(max_length=200, null=True)),
                ('txt06', models.CharField(max_length=200, null=True)),
                ('txt07', models.CharField(max_length=200, null=True)),
                ('txt08', models.CharField(max_length=200, null=True)),
                ('txt09', models.CharField(max_length=200, null=True)),
                ('txt10', models.CharField(max_length=200, null=True)),
                ('txt11', models.CharField(max_length=200, null=True)),
                ('txt12', models.CharField(max_length=200, null=True)),
                ('txt13', models.CharField(max_length=200, null=True)),
                ('txt14', models.CharField(max_length=200, null=True)),
                ('txt15', models.CharField(max_length=200, null=True)),
                ('txt16', models.CharField(max_length=200, null=True)),
                ('txt17', models.CharField(max_length=200, null=True)),
                ('txt18', models.CharField(max_length=200, null=True)),
                ('txt19', models.CharField(max_length=200, null=True)),
                ('txt20', models.CharField(max_length=200, null=True)),
                ('txt21', models.CharField(max_length=200, null=True)),
                ('txt22', models.CharField(max_length=200, null=True)),
                ('txt23', models.CharField(max_length=200, null=True)),
                ('txt24', models.CharField(max_length=200, null=True)),
                ('txt25_1', models.CharField(max_length=200, null=True)),
                ('txt25_2', models.CharField(max_length=200, null=True)),
                ('txt25_3', models.CharField(max_length=200, null=True)),
                ('txt25_4', models.CharField(max_length=200, null=True)),
                ('txt25_5', models.CharField(max_length=200, null=True)),
                ('txt26', models.CharField(max_length=200, null=True)),
                ('txt27', models.CharField(max_length=200, null=True)),
                ('txt28', models.CharField(max_length=200, null=True)),
                ('txt29', models.CharField(max_length=800, null=True)),
                ('txt30', models.CharField(max_length=200, null=True)),
                ('txt31', models.CharField(max_length=200, null=True)),
                ('txt32_1', models.CharField(max_length=200, null=True)),
                ('txt32_2', models.CharField(max_length=200, null=True)),
                ('txt32_3', models.CharField(max_length=200, null=True)),
                ('txt32_4', models.CharField(max_length=200, null=True)),
                ('txt33_1', models.CharField(max_length=200, null=True)),
                ('txt33_2', models.CharField(max_length=200, null=True)),
                ('txt34', models.CharField(max_length=200, null=True)),
                ('txt35', models.CharField(max_length=200, null=True)),
                ('txt37', models.CharField(max_length=200, null=True)),
                ('txt38', models.CharField(max_length=200, null=True)),
                ('txt40', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('procedimiento', models.CharField(max_length=30)),
                ('cartaporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cartaportes.cartaporte')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo', to='appdocs.vehiculo')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_manifiestos.manifiestodoc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
