# Generated by Django 5.0.1 on 2024-08-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manifiestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manifiesto',
            table='manifiesto',
        ),
        migrations.AlterModelTable(
            name='manifiestodoc',
            table='manifiestodoc',
        ),
    ]
