# Generated by Django 5.0.1 on 2024-08-21 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cartaporte', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaporte',
            name='documento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cartaporte.cartaportedoc'),
        ),
    ]
