# Generated by Django 5.0.1 on 2024-09-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cartaporte', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaportedoc',
            name='txt12',
            field=models.CharField(max_length=1400, null=True),
        ),
    ]
