# Generated by Django 5.0.1 on 2024-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cartaporte', '0003_alter_cartaportedoc_txt12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaporte',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
    ]
