# Generated by Django 5.0.1 on 2024-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cartaporte', '0005_alter_cartaporte_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaportedoc',
            name='txt19',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
