# Generated by Django 5.0.1 on 2024-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cartaporte', '0006_alter_cartaportedoc_txt19'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaportedoc',
            name='txt12',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
