# Generated by Django 5.0.1 on 2024-09-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cartaporte', '0007_alter_cartaportedoc_txt12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaporte',
            name='documento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='app_cartaporte.cartaportedoc'),
        ),
    ]
