# Generated by Django 5.0.1 on 2024-08-24 19:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaporteDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('txt0a', models.CharField(max_length=20, null=True)),
                ('txt00', models.CharField(max_length=20, null=True)),
                ('txt01', models.CharField(max_length=200, null=True)),
                ('txt02', models.CharField(max_length=200, null=True)),
                ('txt03', models.CharField(max_length=200, null=True)),
                ('txt04', models.CharField(max_length=200, null=True)),
                ('txt05', models.CharField(max_length=200, null=True)),
                ('txt06', models.CharField(max_length=200, null=True)),
                ('txt07', models.CharField(max_length=200, null=True)),
                ('txt08', models.CharField(max_length=200, null=True)),
                ('txt09', models.CharField(max_length=200, null=True)),
                ('txt10', models.CharField(max_length=200, null=True)),
                ('txt11', models.CharField(max_length=200, null=True)),
                ('txt12', models.CharField(max_length=900, null=True)),
                ('txt13_1', models.CharField(max_length=200, null=True)),
                ('txt13_2', models.CharField(max_length=200, null=True)),
                ('txt14', models.CharField(max_length=200, null=True)),
                ('txt15', models.CharField(max_length=200, null=True)),
                ('txt16', models.CharField(max_length=200, null=True)),
                ('txt17_11', models.CharField(max_length=200, null=True)),
                ('txt17_12', models.CharField(max_length=200, null=True)),
                ('txt17_13', models.CharField(max_length=200, null=True)),
                ('txt17_14', models.CharField(max_length=200, null=True)),
                ('txt17_21', models.CharField(max_length=200, null=True)),
                ('txt17_22', models.CharField(max_length=200, null=True)),
                ('txt17_23', models.CharField(max_length=200, null=True)),
                ('txt17_24', models.CharField(max_length=200, null=True)),
                ('txt17_31', models.CharField(max_length=200, null=True)),
                ('txt17_32', models.CharField(max_length=200, null=True)),
                ('txt17_33', models.CharField(max_length=200, null=True)),
                ('txt17_34', models.CharField(max_length=200, null=True)),
                ('txt17_41', models.CharField(max_length=200, null=True)),
                ('txt17_42', models.CharField(max_length=200, null=True)),
                ('txt17_43', models.CharField(max_length=200, null=True)),
                ('txt17_44', models.CharField(max_length=200, null=True)),
                ('txt18', models.CharField(max_length=200, null=True)),
                ('txt19', models.CharField(max_length=50, null=True)),
                ('txt21', models.CharField(max_length=200, null=True)),
                ('txt22', models.CharField(max_length=300, null=True)),
                ('txt24', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'cartaportedoc',
            },
        ),
        migrations.CreateModel(
            name='Cartaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('pais', models.CharField(max_length=30)),
                ('destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cliente_cartaporte_set_destinatario', to='app_docs.cliente')),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cliente_cartaporte_set_remitente', to='app_docs.cliente')),
            ],
            options={
                'db_table': 'cartaporte',
            },
        ),
    ]
