# Generated by Django 5.0.1 on 2024-09-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroId', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=20)),
                ('tipoId', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('ECUADOR', 'ECUADOR'), ('PERU', 'PERU'), ('OTRO', 'OTRO')], default='COLOMBIA', max_length=50)),
                ('licencia', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.CharField(max_length=50)),
                ('auxiliar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor_principal', to='app_docs.conductor')),
            ],
            options={
                'verbose_name_plural': 'Conductores',
                'db_table': 'conductor',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=20)),
                ('chasis', models.CharField(max_length=50)),
                ('anho', models.CharField(max_length=20)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_docs.conductor')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
    ]
