# Generated by Django 5.0.1 on 2024-10-04 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='fecha_nacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.AddField(
            model_name='conductor',
            name='tipoDoc',
            field=models.CharField(default='CEDULA DE IDENTIDAD', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='remolque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_principal', to='app_docs.vehiculo'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='auxiliar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_principal', to='app_docs.conductor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='app_docs.conductor'),
            preserve_default=False,
        ),
    ]
