# Generated by Django 5.0.1 on 2024-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='conductor',
            name='pais',
            field=models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('ECUADOR', 'ECUADOR'), ('PERU', 'PERU'), ('OTRO', 'OTRO')], default='COLOMBIA', max_length=50),
        ),
    ]
