# Generated by Django 5.0.1 on 2024-09-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EcuapassForm',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_docs.conductor'),
        ),
    ]
