# Generated by Django 5.0.1 on 2024-10-04 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0002_rename_fecha_nacimiento_conductor_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_principal', to='app_docs.conductor'),
        ),
    ]
