# Generated by Django 5.0.1 on 2024-10-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0003_alter_vehiculo_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anho',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='chasis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='pais',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
