# Generated by Django 5.0.1 on 2024-10-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0003_alter_vehiculo_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='conductor',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='conductor',
            field=models.ManyToManyField(related_name='vehiculos', to='app_docs.conductor'),
        ),
    ]
