# Generated by Django 5.0.1 on 2024-10-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0004_alter_vehiculo_anho_alter_vehiculo_chasis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
