# Generated by Django 5.0.1 on 2024-10-22 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0004_remove_vehiculo_conductor_vehiculo_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='conductor',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='conductor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo', to='app_docs.conductor'),
        ),
    ]
