# Generated by Django 5.0.1 on 2024-10-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0005_remove_vehiculo_conductor_vehiculo_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='remolque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo', to='app_docs.vehiculo'),
        ),
    ]
