# Generated by Django 5.0.1 on 2024-10-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0006_alter_vehiculo_remolque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='app_docs.conductor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='remolque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='app_docs.vehiculo'),
        ),
    ]
