# Generated by Django 5.0.1 on 2024-10-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0007_vehiculo_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
