# Generated by Django 5.0.1 on 2024-10-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0008_vehiculo_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
