# Generated by Django 5.0.1 on 2024-10-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0009_rename_fechanacimiento_conductor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='remolque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_principal', to='app_docs.vehiculo'),
        ),
    ]
