# Generated by Django 5.0.1 on 2024-10-07 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0011_alter_vehiculo_remolque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='remolque',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_principal', to='app_docs.vehiculo'),
        ),
    ]
