# Generated by Django 5.0.1 on 2024-05-05 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0013_alter_cartaportedoc_txt22'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaporte',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Empresa_cartaporte_set_destinatario', to='appdocs.empresa'),
        ),
        migrations.AlterField(
            model_name='cartaporte',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Empresa_cartaporte_set_remitente', to='appdocs.empresa'),
        ),
    ]
