# Generated by Django 5.0.1 on 2024-07-29 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cartaportes', '0001_initial'),
        ('appdocs', '0014_cartaporte_destinatario_alter_cartaporte_remitente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaporte',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='cartaporte',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cartaporte',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='cartaporte',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='manifiesto',
            name='cartaporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cartaportes.cartaporte'),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='cartaporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cartaportes.cartaporte'),
        ),
        migrations.DeleteModel(
            name='CartaporteDoc',
        ),
        migrations.DeleteModel(
            name='Cartaporte',
        ),
    ]
