# Generated by Django 5.0.1 on 2024-08-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0015_remove_cartaporte_destinatario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifiesto',
            name='cartaporte',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='vehiculo',
        ),
        migrations.DeleteModel(
            name='ManifiestoDoc',
        ),
        migrations.DeleteModel(
            name='Manifiesto',
        ),
    ]
