# Generated by Django 5.0.1 on 2024-08-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdocs', '0016_remove_manifiesto_cartaporte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracion',
            name='cartaporte',
        ),
        migrations.RemoveField(
            model_name='declaracion',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='declaracion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DeclaracionDoc',
        ),
        migrations.DeleteModel(
            name='Declaracion',
        ),
    ]
