# Generated by Django 5.0.1 on 2024-10-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cartaporte', '0001_initial'),
        ('app_docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifiestoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('txt0a', models.CharField(max_length=20, null=True)),
                ('txt00', models.CharField(max_length=20, null=True)),
                ('txt01', models.CharField(max_length=200, null=True)),
                ('txt02', models.CharField(max_length=200, null=True)),
                ('txt03', models.CharField(max_length=200, null=True)),
                ('txt04', models.CharField(max_length=200, null=True)),
                ('txt05', models.CharField(max_length=200, null=True)),
                ('txt06', models.CharField(max_length=200, null=True)),
                ('txt07', models.CharField(max_length=200, null=True)),
                ('txt08', models.CharField(max_length=200, null=True)),
                ('txt09', models.CharField(max_length=200, null=True)),
                ('txt10', models.CharField(max_length=200, null=True)),
                ('txt11', models.CharField(max_length=200, null=True)),
                ('txt12', models.CharField(max_length=200, null=True)),
                ('txt13', models.CharField(max_length=200, null=True)),
                ('txt14', models.CharField(max_length=200, null=True)),
                ('txt15', models.CharField(max_length=200, null=True)),
                ('txt16', models.CharField(max_length=200, null=True)),
                ('txt17', models.CharField(max_length=200, null=True)),
                ('txt18', models.CharField(max_length=200, null=True)),
                ('txt19', models.CharField(max_length=200, null=True)),
                ('txt20', models.CharField(max_length=200, null=True)),
                ('txt21', models.CharField(max_length=200, null=True)),
                ('txt22', models.CharField(max_length=200, null=True)),
                ('txt23', models.CharField(max_length=200, null=True)),
                ('txt24', models.CharField(max_length=200, null=True)),
                ('txt25_1', models.CharField(max_length=200, null=True)),
                ('txt25_2', models.CharField(max_length=200, null=True)),
                ('txt25_3', models.CharField(max_length=200, null=True)),
                ('txt25_4', models.CharField(max_length=200, null=True)),
                ('txt25_5', models.CharField(max_length=200, null=True)),
                ('txt26', models.CharField(max_length=200, null=True)),
                ('txt27', models.CharField(max_length=200, null=True)),
                ('txt28', models.CharField(max_length=200, null=True)),
                ('txt29', models.CharField(max_length=800, null=True)),
                ('txt30', models.CharField(max_length=200, null=True)),
                ('txt31', models.CharField(max_length=200, null=True)),
                ('txt32_1', models.CharField(max_length=200, null=True)),
                ('txt32_2', models.CharField(max_length=200, null=True)),
                ('txt32_3', models.CharField(max_length=200, null=True)),
                ('txt32_4', models.CharField(max_length=200, null=True)),
                ('txt33_1', models.CharField(max_length=200, null=True)),
                ('txt33_2', models.CharField(max_length=200, null=True)),
                ('txt34', models.CharField(max_length=200, null=True)),
                ('txt35', models.CharField(max_length=200, null=True)),
                ('txt37', models.CharField(max_length=200, null=True)),
                ('txt38', models.CharField(max_length=200, null=True)),
                ('txt40', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'manifiestoform',
            },
        ),
        migrations.CreateModel(
            name='Manifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField(null=True)),
                ('pais', models.CharField(max_length=30)),
                ('referencia', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cartaporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cartaporte.cartaporte')),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor', to='app_docs.conductor')),
            ],
            options={
                'db_table': 'manifiesto',
            },
        ),
    ]
