# Generated by Django 5.0.1 on 2024-09-13 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manifiesto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiesto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='referencia',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
