# Generated by Django 5.0.1 on 2024-09-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_docs', '0002_remove_conductor_nacionalidad_conductor_pais'),
        ('app_manifiesto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiesto',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor', to='app_docs.conductor'),
        ),
    ]
