# Generated by Django 5.0.1 on 2024-09-03 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manifiesto', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiesto',
            name='fecha_emision',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
