# Generated by Django 5.0.1 on 2024-10-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manifiesto', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiestoform',
            name='txt29',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
