# Generated by Django 5.0.1 on 2024-09-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manifiesto', '0003_manifiesto_fecha_creacion_manifiesto_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifiesto',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
